---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ws-assets-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /ws-assets

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-assets-pvc
  namespace: ns-workshop
spec:
  volumeName: ws-assets-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi